import { makeRouteCommands } from "../commands/factory";

/**
 * CLI commands for the full DSAR request lifecycle: intake, capture,
 * verification, delivery, extensions, refusals, appeals, and fulfilment.
 */
export const requestsCommands = makeRouteCommands([
	"requests_create",
	"requests_list",
	"requests_capture",
	"requests_get",
	"requests_timeline",
	"requests_clock_explain",
	"requests_clarifications_request",
	"requests_clarifications_receive",
	"requests_extensions_create",
	"requests_refusals_create",
	"requests_closures_create",
	"requests_acknowledgements_create",
	"requests_requestor_set",
	"requests_authority_submit",
	"requests_authority_approve",
	"requests_authority_reject",
	"requests_verification_request",
	"requests_verification_evidence",
	"requests_verification_evidence_upload",
	"requests_verification_approve",
	"requests_verification_reject",
	"requests_verification_case",
	"requests_delivery_prepare",
	"requests_delivery_address_verify",
	"requests_delivery_step_up_challenge",
	"requests_delivery_step_up_complete",
	"requests_artifacts_download",
	"requests_delivery_logs",
	"requests_fulfilment",
	"requests_fulfilment_callback",
	"requests_manifest_get",
	"requests_manifest_validate",
	"requests_manifest_artifact_upload",
	"requests_manifest_artifact_download",
	"requests_manifest_artifact_replace",
	"requests_appeals_create",
	"requests_appeals_list",
	"requests_appeals_decide",
	"requests_notifications_list",
	"requests_notifications_replay",
	"requests_audit_export",
	"requests_audit_verify",
] as const);
