import type { RouteParityDefinition } from "../types";

/**
 * Mapping from backend HTTP routes to their CLI command equivalents,
 * used by command registration and the interactive wizard to maintain
 * parity between the REST API and the CLI surface.
 */
export const routeParityMap: readonly RouteParityDefinition[] = [
	{
		command: ["init"],
		description: "Initialize runtime context.",
		id: "init_runtime",
		method: "POST",
		path: "/init",
	},
	{
		command: ["status"],
		description: "Get runtime health status.",
		id: "status_health",
		method: "GET",
		path: "/status",
	},
	{
		command: ["subjects", "get", ":subjectId"],
		description: "Get subject profile.",
		id: "subjects_get_profile",
		method: "GET",
		path: "/subjects/{subjectId}",
	},
	{
		command: ["policies", "list"],
		description: "List policy surfaces.",
		id: "policies_list",
		method: "GET",
		path: "/policies",
	},
	{
		command: ["policies", "upgrades", "propose"],
		description: "Propose policy upgrade.",
		id: "policies_upgrades_propose",
		method: "POST",
		path: "/policies/upgrades/propose",
	},
	{
		command: ["policies", "upgrades", "approve", ":proposalId"],
		description: "Approve policy upgrade.",
		id: "policies_upgrades_approve",
		method: "POST",
		path: "/policies/upgrades/{proposalId}/approve",
	},
	{
		command: ["policies", "upgrades", "apply", ":proposalId"],
		description: "Apply policy upgrade.",
		id: "policies_upgrades_apply",
		method: "POST",
		path: "/policies/upgrades/{proposalId}/apply",
	},
	{
		command: ["policies", "custom", "register"],
		description: "Register custom policy pack.",
		id: "policies_custom_register",
		method: "POST",
		path: "/policies/custom/register",
	},
	{
		command: ["policies", "custom", "activate"],
		description: "Activate custom policy pack.",
		id: "policies_custom_activate",
		method: "POST",
		path: "/policies/custom/activate",
	},
	{
		command: ["policies", "custom", "deactivate"],
		description: "Deactivate custom policy pack.",
		id: "policies_custom_deactivate",
		method: "POST",
		path: "/policies/custom/deactivate",
	},
	{
		command: ["webhooks", "inbound", "resend"],
		description: "Handle inbound Resend webhook payload.",
		id: "webhooks_inbound_resend",
		method: "POST",
		path: "/webhooks/inbound/resend",
	},
	{
		command: ["webhooks", "inbound", "slack"],
		description: "Handle inbound Slack webhook payload.",
		id: "webhooks_inbound_slack",
		method: "POST",
		path: "/webhooks/inbound/slack",
	},
	{
		command: ["webhooks", "rotate-key", ":id"],
		description: "Rotate webhook endpoint signing key.",
		id: "webhooks_endpoint_rotate_key",
		method: "POST",
		path: "/webhooks/endpoints/{id}/rotate-key",
	},
	{
		command: ["webhooks", "list"],
		description: "List outbound webhook dispatches.",
		flagHelp: [
			"--status <statuses>      Comma-separated delivery statuses (e.g. failed)",
			"--endpoint-id <id>       Filter by configured webhook endpoint id",
			"--created-after <iso>    Only include attempts created after this time",
			"--created-before <iso>   Only include attempts created before this time",
			"--limit <n>              Page size, 1-500 (default 50)",
			"--offset <n>             Zero-based page offset",
		],
		id: "webhooks_dispatches_list",
		method: "GET",
		path: "/webhooks/dispatches",
	},
	{
		command: ["webhooks", "replay", ":id"],
		description: "Replay outbound webhook dispatch.",
		flagHelp: ["--idempotency-key <key>  Replay dedupe key (required)"],
		id: "webhooks_dispatches_replay",
		method: "POST",
		path: "/webhooks/dispatches/{id}/replay",
	},
	{
		command: ["webhooks", "replay-all"],
		description: "Replay failed outbound webhook dispatches.",
		flagHelp: [
			"--idempotency-key <key>  Bulk replay dedupe key (required)",
			"--status <status>        Must be 'failed' when present",
			"--endpoint-id <id>       Filter by configured webhook endpoint id",
			"--created-after <iso>    Only replay attempts created after this time",
			"--created-before <iso>   Only replay attempts created before this time",
			"--limit <n>              Maximum dispatches to replay, 1-100",
		],
		id: "webhooks_dispatches_replay_bulk",
		method: "POST",
		path: "/webhooks/dispatches/replay",
	},
	{
		command: ["requests", "create"],
		description: "Create request.",
		id: "requests_create",
		method: "POST",
		path: "/requests",
	},
	{
		command: ["requests", "list"],
		description: "List request queue.",
		id: "requests_list",
		method: "GET",
		path: "/requests",
	},
	{
		command: ["requests", "capture"],
		description: "Capture request intake.",
		id: "requests_capture",
		method: "POST",
		path: "/requests/capture",
	},
	{
		command: ["requests", "get", ":id"],
		description: "Get request.",
		id: "requests_get",
		method: "GET",
		path: "/requests/{id}",
	},
	{
		command: ["requests", "timeline", ":id"],
		description: "Get request timeline.",
		id: "requests_timeline",
		method: "GET",
		path: "/requests/{id}/timeline",
	},
	{
		command: ["requests", "clock", "explain", ":id"],
		description: "Explain legal clock.",
		id: "requests_clock_explain",
		method: "GET",
		path: "/requests/{id}/clock/explain",
	},
	{
		command: ["requests", "clarifications", "request", ":id"],
		description: "Request clarification.",
		id: "requests_clarifications_request",
		method: "POST",
		path: "/requests/{id}/clarifications/request",
	},
	{
		command: ["requests", "clarifications", "receive", ":id"],
		description: "Receive clarification.",
		id: "requests_clarifications_receive",
		method: "POST",
		path: "/requests/{id}/clarifications/receive",
	},
	{
		command: ["requests", "extensions", "create", ":id"],
		description: "Create extension.",
		id: "requests_extensions_create",
		method: "POST",
		path: "/requests/{id}/extensions",
	},
	{
		command: ["requests", "refusals", "create", ":id"],
		description: "Refuse request.",
		id: "requests_refusals_create",
		method: "POST",
		path: "/requests/{id}/refusals",
	},
	{
		command: ["requests", "closures", "create", ":id"],
		description: "Close request.",
		id: "requests_closures_create",
		method: "POST",
		path: "/requests/{id}/closures",
	},
	{
		command: ["requests", "acknowledgements", "create", ":id"],
		description: "Create acknowledgement.",
		id: "requests_acknowledgements_create",
		method: "POST",
		path: "/requests/{id}/acknowledgements",
	},
	{
		command: ["requests", "requestor", "set", ":id"],
		description: "Set requestor.",
		id: "requests_requestor_set",
		method: "PUT",
		path: "/requests/{id}/requestor",
	},
	{
		command: ["requests", "authority", "submit", ":id"],
		description: "Submit authority.",
		id: "requests_authority_submit",
		method: "POST",
		path: "/requests/{id}/authority/submit",
	},
	{
		command: ["requests", "authority", "approve", ":id"],
		description: "Approve authority.",
		id: "requests_authority_approve",
		method: "POST",
		path: "/requests/{id}/authority/approve",
	},
	{
		command: ["requests", "authority", "reject", ":id"],
		description: "Reject authority.",
		id: "requests_authority_reject",
		method: "POST",
		path: "/requests/{id}/authority/reject",
	},
	{
		command: ["requests", "verification", "request", ":id"],
		description: "Create verification case.",
		id: "requests_verification_request",
		method: "POST",
		path: "/requests/{id}/verification/request",
	},
	{
		command: ["requests", "verification", "evidence", ":id"],
		description: "Attach verification evidence.",
		id: "requests_verification_evidence",
		method: "POST",
		path: "/requests/{id}/verification/evidence",
	},
	{
		command: ["requests", "verification", "evidence-upload", ":id"],
		description: "Upload verification evidence file.",
		id: "requests_verification_evidence_upload",
		method: "POST",
		path: "/requests/{id}/verification/evidence/upload",
	},
	{
		command: ["requests", "verification", "approve", ":id"],
		description: "Approve verification.",
		id: "requests_verification_approve",
		method: "POST",
		path: "/requests/{id}/verification/approve",
	},
	{
		command: ["requests", "verification", "reject", ":id"],
		description: "Reject verification.",
		id: "requests_verification_reject",
		method: "POST",
		path: "/requests/{id}/verification/reject",
	},
	{
		command: ["requests", "verification", "case", ":id"],
		description: "Get verification case.",
		id: "requests_verification_case",
		method: "GET",
		path: "/requests/{id}/verification-case",
	},
	{
		command: ["requests", "delivery", "prepare", ":id"],
		description: "Prepare delivery.",
		id: "requests_delivery_prepare",
		method: "POST",
		path: "/requests/{id}/delivery/prepare",
	},
	{
		command: ["requests", "delivery", "address-verify", ":id"],
		description: "Verify delivery address.",
		id: "requests_delivery_address_verify",
		method: "POST",
		path: "/requests/{id}/delivery/address/verify",
	},
	{
		command: ["requests", "delivery", "step-up-challenge", ":id"],
		description: "Start step-up challenge.",
		id: "requests_delivery_step_up_challenge",
		method: "POST",
		path: "/requests/{id}/delivery/step-up/challenge",
	},
	{
		command: ["requests", "delivery", "step-up-complete", ":id"],
		description: "Complete step-up challenge.",
		id: "requests_delivery_step_up_complete",
		method: "POST",
		path: "/requests/{id}/delivery/step-up/complete",
	},
	{
		command: ["requests", "artifacts", "download", ":id", ":artifactId"],
		description: "Download artifact.",
		id: "requests_artifacts_download",
		method: "GET",
		path: "/requests/{id}/artifacts/{artifactId}/download",
	},
	{
		command: ["requests", "delivery", "logs", ":id"],
		description: "Get delivery logs.",
		id: "requests_delivery_logs",
		method: "GET",
		path: "/requests/{id}/delivery/logs",
	},
	{
		command: ["requests", "fulfilment", "create", ":id"],
		description: "Fulfil request.",
		id: "requests_fulfilment",
		method: "POST",
		path: "/requests/{id}/fulfilment",
	},
	{
		command: ["requests", "fulfilment", "callback", ":id"],
		description: "Fulfilment callback.",
		id: "requests_fulfilment_callback",
		method: "POST",
		path: "/requests/{id}/fulfilment/callback",
	},
	{
		command: ["requests", "manifest", "get", ":id"],
		description: "Get manifest.",
		id: "requests_manifest_get",
		method: "GET",
		path: "/requests/{id}/manifest",
	},
	{
		command: ["requests", "manifest", "validate", ":id"],
		description: "Validate manifest.",
		id: "requests_manifest_validate",
		method: "POST",
		path: "/requests/{id}/manifest/validate",
	},
	{
		command: ["requests", "manifest", "artifact-upload", ":id"],
		description: "Upload manifest artifact.",
		id: "requests_manifest_artifact_upload",
		method: "POST",
		path: "/requests/{id}/manifest/artifact/upload",
	},
	{
		command: ["requests", "manifest", "artifact-download", ":id"],
		description: "Download manifest artifact.",
		id: "requests_manifest_artifact_download",
		method: "GET",
		path: "/requests/{id}/manifest/artifact/download",
	},
	{
		command: ["requests", "manifest", "artifact-replace", ":id", ":artifactId"],
		description: "Replace manifest artifact.",
		id: "requests_manifest_artifact_replace",
		method: "PUT",
		path: "/requests/{id}/manifest/artifact/{artifactId}/replace",
	},
	{
		command: ["requests", "appeals", "create", ":id"],
		description: "Create appeal.",
		id: "requests_appeals_create",
		method: "POST",
		path: "/requests/{id}/appeals",
	},
	{
		command: ["requests", "appeals", "list", ":id"],
		description: "List appeals.",
		id: "requests_appeals_list",
		method: "GET",
		path: "/requests/{id}/appeals",
	},
	{
		command: ["requests", "appeals", "decide", ":id", ":appealId"],
		description: "Decide appeal.",
		id: "requests_appeals_decide",
		method: "POST",
		path: "/requests/{id}/appeals/{appealId}/decide",
	},
	{
		command: ["requests", "notifications", "list", ":id"],
		description: "List request notifications.",
		id: "requests_notifications_list",
		method: "GET",
		path: "/requests/{id}/notifications",
	},
	{
		command: ["requests", "notifications", "replay", ":id", ":eventId"],
		description: "Replay a notification event.",
		id: "requests_notifications_replay",
		method: "POST",
		path: "/requests/{id}/notifications/{eventId}/replay",
	},
	{
		command: ["tenants", "retention", "get", ":tenantId"],
		description: "Get tenant retention.",
		id: "tenants_retention_get",
		method: "GET",
		path: "/tenants/{tenantId}/retention",
	},
	{
		command: ["tenants", "retention", "put", ":tenantId"],
		description: "Set tenant retention.",
		id: "tenants_retention_put",
		method: "PUT",
		path: "/tenants/{tenantId}/retention",
	},
	{
		command: ["requests", "audit", "export", ":id"],
		description: "Export audit trail.",
		id: "requests_audit_export",
		method: "GET",
		path: "/requests/{id}/audit/export",
	},
	{
		command: ["requests", "audit", "verify", ":id"],
		description: "Verify audit trail.",
		id: "requests_audit_verify",
		method: "POST",
		path: "/requests/{id}/audit/verify",
	},
	{
		command: ["audit", "list"],
		description: "List audit events with filters.",
		id: "audit_list",
		method: "GET",
		path: "/audit",
	},
	{
		command: ["audit", "export"],
		description: "Export tenant audit trail.",
		id: "audit_export",
		method: "GET",
		path: "/audit/export",
	},
] as const;

/**
 * Backend capabilities that are defined but not yet exposed through
 * the CLI. Entries here are excluded from command registration until
 * their implementation is complete.
 */
export const deferredCapabilities = [] as const;
